projects:
  receiptAPI:
    schemaPath: lib/RCgraphql/RCschema.json
    includes:
      - api/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: api/graphql
extensions:
  amplify:
    version: 3
